# Generated by Django 2.2.4 on 2019-08-24 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bubble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.SlugField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('reset_token', models.TextField(blank=True, null=True)),
                ('hearts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('quiztype', models.IntegerField(choices=[(0, 'Sprint'), (1, 'Marathon')])),
                ('active', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=10)),
                ('questions_answered', models.IntegerField(default=0)),
                ('questions_total', models.IntegerField(default=0)),
                ('question_ids', models.TextField()),
                ('startdatetime', models.DateTimeField(auto_now_add=True)),
                ('enddatetime', models.DateTimeField(blank=True, null=True)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('helperdatetime', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('joker_fiftyfifty_available', models.BooleanField(default=True)),
                ('joker_audience_available', models.BooleanField(default=True)),
                ('joker_timestop_available', models.BooleanField(default=True)),
                ('timestop_active', models.BooleanField(default=False)),
                ('can_send_love', models.BooleanField(default=True)),
                ('bubble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='quiz.Bubble')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_a', models.TextField()),
                ('answer_b', models.TextField()),
                ('answer_c', models.TextField()),
                ('answer_d', models.TextField()),
                ('chosen_answers_count', models.TextField(default='{"a": 0, "b": 0, "c": 0, "d": 0}')),
                ('correct_answer', models.CharField(choices=[('a', 'Answer A'), ('b', 'Answer B'), ('c', 'Answer C'), ('d', 'Answer D')], max_length=1)),
                ('difficulty', models.IntegerField(choices=[(0, 'Easy'), (1, 'Intermediate'), (2, 'Challenging'), (3, 'Expert')])),
                ('explanation', models.TextField(help_text='Provide some more context about the right answer and maybe frame it in the larger picture of the other answers. This explanation will be displayed after an answer was picked, irrepective of whether the right or wrong answer was chosen.')),
                ('contributor', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bubble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.Bubble')),
            ],
        ),
    ]
