# Generated by Django 2.2.4 on 2019-08-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bubble',
            name='reset_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
