# Generated by Django 2.2.4 on 2019-08-19 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_access',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='space',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 19, 13, 33, 41, 941316, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='enddatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
