# Generated by Django 2.2.4 on 2019-08-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='started',
            new_name='startdate',
        ),
        migrations.AddField(
            model_name='game',
            name='enddate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
