# Generated by Django 2.2.4 on 2019-08-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_bubble_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='intermezzo_state',
        ),
        migrations.AddField(
            model_name='bubble',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='sent_love',
            field=models.BooleanField(default=False),
        ),
    ]
