# Generated by Django 2.2.4 on 2019-08-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190814_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='enddate',
            new_name='enddatetime',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='startdate',
            new_name='startdatetime',
        ),
    ]
