# Generated by Django 2.2.4 on 2019-08-19 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190819_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 19, 15, 55, 3, 613718, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
