# Generated by Django 2.2.4 on 2019-08-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190825_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions_index',
            field=models.IntegerField(default=0),
        ),
    ]
