# Generated by Django 2.2.4 on 2019-08-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='chosen_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='chosen_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='chosen_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='chosen_d',
        ),
        migrations.AddField(
            model_name='game',
            name='joker_fiftyfifty_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='chosen_answers_count',
            field=models.TextField(default='{"a": 0, "b": 0, "c": 0, "d": 0}'),
        ),
    ]
