# Generated by Django 2.2.4 on 2019-08-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190824_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='sent_love',
        ),
        migrations.AddField(
            model_name='quiz',
            name='can_send_love',
            field=models.BooleanField(default=True),
        ),
    ]
