# Generated by Django 2.2.4 on 2019-08-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190814_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.CharField(default='anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='questions_answered',
            field=models.IntegerField(default=0),
        ),
    ]
