# Generated by Django 2.2.4 on 2019-08-28 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_questions_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bubble',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='uuid',
        ),
        migrations.AddField(
            model_name='quiz',
            name='heartbeat_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
