# Generated by Django 2.2.4 on 2019-08-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190820_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='joker_audience_available',
            field=models.BooleanField(default=True),
        ),
    ]
