# Generated by Django 2.2.4 on 2019-08-28 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190828_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='bubble',
            name='last_cleanup',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
