# Generated by Django 2.2.4 on 2019-08-16 08:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190815_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='game',
            name='last_accessed',
        ),
        migrations.AddField(
            model_name='game',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.CharField(max_length=30),
        ),
    ]
