# Generated by Django 2.2.4 on 2019-08-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_bubble_last_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bubble',
            name='last_cleanup',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='heartbeat_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
