# Generated by Django 2.2.4 on 2019-08-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_game_joker_audience_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='helper_reset_timer_nextround',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='joker_timestop_available',
            field=models.BooleanField(default=True),
        ),
    ]
