# Generated by Django 2.2.4 on 2019-08-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190816_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='helperdatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
