# Generated by Django 2.2.4 on 2019-08-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190821_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='helper_reset_timer_nextround',
        ),
        migrations.AddField(
            model_name='game',
            name='increment_duration_at_roundstart',
            field=models.BooleanField(default=True),
        ),
    ]
