# Generated by Django 2.2.4 on 2019-08-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190828_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quizstate',
            field=models.IntegerField(choices=[(0, 'Initialized'), (1, 'In progress'), (2, 'Finished')], default=0),
        ),
    ]
