# Generated by Django 2.2.4 on 2019-08-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_quizstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='active',
        ),
    ]
