# Generated by Django 2.2.4 on 2019-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20190816_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
