# Generated by Django 2.2.4 on 2019-08-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190816_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='questions_answered',
            new_name='question_index',
        ),
    ]
