# Generated by Django 2.2.4 on 2019-08-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20190816_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('a', 'Answer A'), ('b', 'Answer B'), ('c', 'Answer C'), ('d', 'Answer D')], max_length=1),
        ),
    ]
