# Generated by Django 2.2.4 on 2019-08-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20190816_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='question_index',
            new_name='questions_answered',
        ),
    ]
