# Generated by Django 2.2.4 on 2019-08-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20190817_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='intermezzo_state',
            field=models.BooleanField(default=True),
        ),
    ]
