# Generated by Django 2.2.4 on 2019-08-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_game_intermezzo_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='questions_total',
            field=models.IntegerField(default=0),
        ),
    ]
