# Generated by Django 2.2.4 on 2019-08-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_game_questions_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='contributor',
        ),
    ]
