# Generated by Django 2.2.4 on 2019-08-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20190819_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.CharField(max_length=10),
        ),
    ]
